// <auto-generated />
namespace Himac.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2c : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2c));
        
        string IMigrationMetadata.Id
        {
            get { return "201809130606306_2c"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
